export enum Chain {
    ARBITRUM = "Arbitrum",
    AVALANCHE = "Avalanche",
    BASE = "Base",
    BITCOIN = "Bitcoin",
    BITCOINCASH = "BitcoinCash",
    BLAST = "Blast",
    BSCCHAIN = "BSC",
    CRONOSCHAIN = "CronosChain",
    DASH = "Dash",
    DOGECOIN = "Dogecoin",
    DYDX = "Dydx",
    ETHEREUM = "Ethereum",
    GAIACHAIN = "Cosmos",
    KUJIRA = "Kujira",
    LITECOIN = "Litecoin",
    MAYACHAIN = "MayaChain",
    OPTIMISM = "Optimism",
    POLKADOT = "Polkadot",
    POLYGON = "Polygon",
    SOLANA = "Solana",
    SUI = "Sui",
    THORCHAIN = "THORChain",
    ZKSYNC = "Zksync",
  }